import { Platform, StyleSheet } from 'react-native';

export const colors = {
  background: '#F6F7F9',
  darkBackground: '#0A1114',
  surface: '#FFFFFF',
  ink: '#172026',
  muted: '#66727F',
  line: '#E2E7EC',
  teal: '#0E7C7B',
  tealSoft: '#DFF3F0',
  coral: '#D8675E',
  coralSoft: '#FBE6E2',
  gold: '#B7822C',
  goldSoft: '#F7EBCB',
  green: '#2F8F62',
  greenSoft: '#DFF2E8',
  slateSoft: '#EEF2F5',
};

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  safeAreaDark: {
    backgroundColor: colors.darkBackground,
  },
  appShell: {
    flex: 1,
    backgroundColor: colors.background,
  },
  appShellDark: {
    backgroundColor: colors.darkBackground,
  },
  navigatorBody: {
    flex: 1,
    backgroundColor: colors.background,
  },
  navigatorBodyDark: {
    backgroundColor: colors.darkBackground,
  },
  persistentTabBar: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: Platform.OS === 'ios' ? 10 : 8,
    height: Platform.OS === 'ios' ? 76 : 68,
    paddingTop: 8,
    paddingBottom: Platform.OS === 'ios' ? 14 : 8,
    backgroundColor: 'rgba(255, 255, 255, 0.74)',
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.62)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.58)',
    borderRadius: 26,
    flexDirection: 'row',
    zIndex: 20,
    overflow: 'hidden',
    shadowColor: colors.ink,
    shadowOpacity: 0.16,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
    elevation: 18,
    ...(Platform.OS === 'web'
      ? ({
          backdropFilter: 'blur(22px) saturate(1.4)',
          WebkitBackdropFilter: 'blur(22px) saturate(1.4)',
        } as object)
      : {}),
  },
  persistentTabItem: {
    flex: 1,
    minWidth: 0,
    minHeight: 56,
    paddingVertical: 3,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
  },
  persistentTabLabel: {
    color: colors.muted,
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '600',
  },
  persistentTabLabelActive: {
    color: colors.coral,
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'android' ? 18 : 8,
    paddingBottom: 14,
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 14,
  },
  headerIdentity: {
    flex: 1,
    minWidth: 0,
  },
  headerActions: {
    alignItems: 'flex-end',
    gap: 4,
  },
  logo: {
    color: colors.ink,
    fontSize: 24,
    fontWeight: '600',
    letterSpacing: 0,
  },
  logoImage: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.slateSoft,
  },
  headerMeta: {
    color: colors.muted,
    fontSize: 12,
    marginTop: 2,
  },
  roleSwitch: {
    flexDirection: 'row',
    backgroundColor: colors.slateSoft,
    borderRadius: 14,
    padding: 3,
  },
  segmentButton: {
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 11,
  },
  segmentButtonActive: {
    backgroundColor: colors.ink,
  },
  segmentButtonText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '700',
  },
  segmentButtonTextActive: {
    color: colors.surface,
  },
  headerLogout: {
    paddingHorizontal: 4,
    paddingVertical: 3,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  headerLogoutText: {
    color: colors.coral,
    fontSize: 12,
    fontWeight: '600',
  },
  content: {
    padding: 20,
    paddingBottom: 118,
  },
  minimalCatalogContent: {
    flexGrow: 1,
    padding: 0,
    paddingBottom: 0,
    backgroundColor: colors.darkBackground,
  },
  catalogFullscreenHost: {
    flex: 1,
    backgroundColor: colors.darkBackground,
  },
  vendorDetailContent: {
    padding: 0,
    paddingBottom: 0,
    backgroundColor: colors.darkBackground,
  },
  onboardingContent: {
    padding: 20,
    paddingBottom: 40,
    gap: 16,
  },
  onboardingHero: {
    minHeight: 260,
    backgroundColor: colors.ink,
    borderRadius: 28,
    padding: 22,
    gap: 12,
    justifyContent: 'flex-end',
  },
  consentRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    paddingHorizontal: 2,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxSelected: {
    backgroundColor: colors.teal,
    borderColor: colors.teal,
  },
  checkboxMark: {
    color: colors.surface,
    fontSize: 15,
    fontWeight: '700',
  },
  consentText: {
    flex: 1,
    color: colors.muted,
    fontSize: 13,
    lineHeight: 19,
  },
  screenStack: {
    gap: 16,
  },
  vendorDetailStack: {
    gap: 0,
    backgroundColor: colors.darkBackground,
  },
  heroPanel: {
    backgroundColor: colors.ink,
    borderRadius: 28,
    padding: 22,
    gap: 12,
  },
  vendorHero: {
    backgroundColor: colors.teal,
    borderRadius: 28,
    padding: 22,
    gap: 12,
  },
  eyebrow: {
    color: colors.goldSoft,
    fontSize: 13,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0,
  },
  heroTitle: {
    color: colors.surface,
    fontSize: 28,
    lineHeight: 34,
    fontWeight: '700',
    letterSpacing: 0,
  },
  heroText: {
    color: '#D7DEE5',
    fontSize: 15,
    lineHeight: 22,
  },
  metricGrid: {
    flexDirection: 'row',
    gap: 10,
  },
  metricCard: {
    flex: 1,
    backgroundColor: colors.surface,
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.line,
    gap: 4,
  },
  metricAccent: {
    width: 26,
    height: 4,
    borderRadius: 6,
    marginBottom: 8,
  },
  tealAccent: {
    backgroundColor: colors.teal,
  },
  coralAccent: {
    backgroundColor: colors.coral,
  },
  goldAccent: {
    backgroundColor: colors.gold,
  },
  metricValue: {
    color: colors.ink,
    fontSize: 20,
    fontWeight: '700',
  },
  metricLabel: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '700',
  },
  sectionHeader: {
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  sectionTitle: {
    color: colors.ink,
    fontSize: 19,
    fontWeight: '700',
  },
  horizontalList: {
    gap: 10,
    paddingRight: 20,
  },
  categoryTile: {
    width: 140,
    minHeight: 92,
    backgroundColor: colors.surface,
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.line,
    justifyContent: 'space-between',
  },
  categoryMark: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.coralSoft,
    borderWidth: 6,
    borderColor: colors.coral,
  },
  categoryIcon: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: colors.coralSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryTitle: {
    color: colors.ink,
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '600',
  },
  toolGrid: {
    flexDirection: 'row',
    gap: 10,
  },
  toolCard: {
    flex: 1,
    backgroundColor: colors.surface,
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.line,
    minHeight: 106,
    gap: 7,
  },
  toolIcon: {
    width: 38,
    height: 38,
    borderRadius: 8,
    backgroundColor: colors.tealSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  screenTitle: {
    color: colors.ink,
    fontSize: 26,
    fontWeight: '700',
    letterSpacing: 0,
  },
  screenSubtitle: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 4,
  },
  searchInput: {
    backgroundColor: colors.surface,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: 16,
    paddingVertical: 14,
    color: colors.ink,
    fontSize: 15,
  },
  searchBox: {
    position: 'relative',
    justifyContent: 'center',
  },
  searchField: {
    paddingLeft: 46,
    paddingRight: 44,
  },
  searchIcon: {
    position: 'absolute',
    left: 16,
    zIndex: 2,
  },
  searchClearButton: {
    position: 'absolute',
    right: 9,
    width: 34,
    height: 34,
    borderRadius: 8,
    backgroundColor: colors.slateSoft,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  catalogModeSwitch: {
    minHeight: 48,
    borderRadius: 8,
    backgroundColor: colors.slateSoft,
    padding: 4,
    flexDirection: 'row',
    gap: 4,
  },
  catalogModeButton: {
    flex: 1,
    minHeight: 40,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  catalogModeButtonActive: {
    backgroundColor: colors.ink,
  },
  catalogModeButtonText: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '600',
  },
  catalogModeButtonTextActive: {
    color: colors.surface,
  },
  codeInput: {
    minHeight: 64,
    textAlign: 'center',
    fontSize: 28,
    fontWeight: '700',
    letterSpacing: 0,
  },
  fieldLabel: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '600',
    marginBottom: -8,
  },
  textareaInput: {
    minHeight: 92,
    textAlignVertical: 'top',
  },
  chipRow: {
    gap: 8,
    paddingRight: 20,
  },
  filterChip: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.line,
  },
  filterChipActive: {
    backgroundColor: colors.teal,
    borderColor: colors.teal,
  },
  filterChipText: {
    color: colors.muted,
    fontWeight: '600',
    fontSize: 13,
  },
  filterChipTextActive: {
    color: colors.surface,
  },
  filterHeader: {
    minHeight: 42,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  filterToggle: {
    minHeight: 42,
    paddingHorizontal: 13,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  filterToggleActive: {
    backgroundColor: colors.ink,
    borderColor: colors.ink,
  },
  filterToggleText: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '600',
  },
  filterToggleTextActive: {
    color: colors.surface,
  },
  activeFilterBadge: {
    minWidth: 21,
    height: 21,
    paddingHorizontal: 6,
    borderRadius: 11,
    backgroundColor: colors.coral,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeFilterBadgeText: {
    color: colors.surface,
    fontSize: 11,
    fontWeight: '600',
  },
  resetFilters: {
    minHeight: 40,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 4,
  },
  filterPanel: {
    paddingVertical: 14,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: colors.line,
    gap: 18,
  },
  filterGroup: {
    gap: 10,
  },
  filterGroupTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  filterGroupTitle: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '600',
  },
  filterOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  resultBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  resultText: {
    color: colors.ink,
    fontWeight: '700',
  },
  resultSort: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '700',
  },
  choiceDeck: {
    gap: 14,
  },
  choiceProgressRow: {
    minHeight: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  choiceCard: {
    height: 388,
    borderRadius: 24,
    overflow: 'hidden',
    backgroundColor: colors.ink,
    borderWidth: 1,
    borderColor: colors.line,
    shadowColor: colors.ink,
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 3,
  },
  choiceCardImage: {
    width: '100%',
    height: '100%',
  },
  choiceCardShade: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'rgba(23, 32, 38, 0.24)',
  },
  choiceSwipeBadge: {
    position: 'absolute',
    top: 24,
    minWidth: 82,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 3,
    backgroundColor: 'rgba(255, 255, 255, 0.82)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 3,
  },
  choiceYesBadge: {
    left: 18,
    borderColor: colors.green,
    transform: [{ rotate: '-10deg' }],
  },
  choiceNoBadge: {
    right: 18,
    borderColor: colors.coral,
    transform: [{ rotate: '10deg' }],
  },
  choiceSwipeText: {
    fontSize: 22,
    lineHeight: 26,
    fontWeight: '700',
    letterSpacing: 0,
  },
  choiceYesText: {
    color: colors.green,
  },
  choiceNoText: {
    color: colors.coral,
  },
  choiceAvailabilityPill: {
    position: 'absolute',
    top: 14,
    right: 14,
    maxWidth: 168,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 8,
    backgroundColor: colors.goldSoft,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
  },
  choiceAvailabilityText: {
    flexShrink: 1,
    color: colors.gold,
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '600',
  },
  choiceCardBody: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 90,
    gap: 9,
  },
  choiceCategoryPill: {
    paddingVertical: 7,
    paddingHorizontal: 10,
    borderRadius: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.88)',
  },
  choiceCategoryText: {
    color: colors.teal,
    fontSize: 12,
    fontWeight: '600',
  },
  choiceTitle: {
    color: colors.surface,
    fontSize: 28,
    lineHeight: 33,
    fontWeight: '700',
    letterSpacing: 0,
  },
  choiceMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 12,
  },
  choiceMetaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  choiceMetaText: {
    color: colors.surface,
    fontSize: 13,
    fontWeight: '600',
  },
  choicePrice: {
    color: colors.surface,
    fontSize: 17,
    lineHeight: 22,
    fontWeight: '600',
  },
  choiceActionRow: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 16,
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  choiceRoundButton: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.line,
    alignItems: 'center',
    justifyContent: 'center',
  },
  choiceSkipButton: {
    backgroundColor: colors.coralSoft,
    borderColor: colors.coralSoft,
  },
  choiceSaveButton: {
    backgroundColor: colors.surface,
  },
  choiceSaveButtonActive: {
    backgroundColor: colors.coralSoft,
    borderColor: colors.coralSoft,
  },
  choiceOpenButton: {
    minHeight: 54,
    paddingHorizontal: 22,
    borderRadius: 27,
    backgroundColor: colors.teal,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  choiceOpenButtonText: {
    color: colors.surface,
    fontSize: 14,
    fontWeight: '600',
  },
  choiceEmptyCard: {
    minHeight: 280,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
    padding: 18,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  choiceResetButton: {
    minHeight: 44,
    paddingHorizontal: 14,
    borderRadius: 8,
    backgroundColor: colors.tealSoft,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    marginTop: 4,
  },
  categoryChoiceWrap: {
    gap: 0,
    backgroundColor: colors.darkBackground,
  },
  categoryChoiceHeader: {
    minHeight: 28,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  categoryChoiceGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    rowGap: 0,
  },
  categoryChoiceCard: {
    width: '50%',
    height: 214,
    borderRadius: 0,
    overflow: 'hidden',
    backgroundColor: colors.ink,
    borderWidth: 0,
  },
  categoryChoiceCardDisabled: {
    opacity: 0.45,
  },
  categoryChoiceImage: {
    width: '100%',
    height: '100%',
  },
  categoryChoiceShade: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'rgba(23, 32, 38, 0.26)',
  },
  categoryChoiceCopy: {
    position: 'absolute',
    left: 10,
    right: 10,
    bottom: 10,
    gap: 3,
  },
  categoryChoiceTitle: {
    color: colors.surface,
    fontSize: 18,
    lineHeight: 22,
    fontWeight: '700',
  },
  categoryChoiceMeta: {
    color: '#D7DEE5',
    fontSize: 12,
    fontWeight: '600',
  },
  shortsShell: {
    flex: 1,
    minHeight: '100%',
    borderRadius: 0,
    overflow: 'hidden',
    backgroundColor: colors.darkBackground,
    position: 'relative',
  },
  shortsAnimatedScene: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: colors.darkBackground,
  },
  shortsMedia: {
    width: '100%',
    height: '100%',
  },
  shortsVideo: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    width: '100%',
    height: '100%',
  },
  shortsShade: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.22)',
  },
  shortsSwipeLayer: {
    position: 'absolute',
    top: 92,
    right: 0,
    bottom: 154,
    left: 0,
    zIndex: 1,
  },
  shortsTopBar: {
    position: 'absolute',
    top: 22,
    left: 18,
    right: 18,
    minHeight: 69,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 18,
    zIndex: 3,
  },
  shortsTopButton: {
    minHeight: 69,
    paddingHorizontal: 22,
    borderRadius: 35,
    backgroundColor: 'rgba(23, 32, 38, 0.64)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 13,
  },
  shortsTopButtonText: {
    color: colors.surface,
    fontSize: 20,
    fontWeight: '600',
  },
  shortsCarouselDots: {
    position: 'absolute',
    top: 114,
    left: 0,
    right: 0,
    minHeight: 25,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    zIndex: 3,
  },
  shortsCarouselDot: {
    width: 11,
    height: 11,
    borderRadius: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.48)',
  },
  shortsCarouselDotActive: {
    width: 32,
    backgroundColor: colors.surface,
  },
  shortsPlayBadge: {
    position: 'absolute',
    top: '38%',
    left: '50%',
    width: 102,
    height: 102,
    marginLeft: -51,
    borderRadius: 51,
    backgroundColor: 'rgba(23, 32, 38, 0.48)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  shortsActionRail: {
    position: 'absolute',
    right: 18,
    bottom: 212,
    width: 102,
    alignItems: 'center',
    gap: 25,
    zIndex: 3,
  },
  shortsAvatar: {
    width: 95,
    height: 95,
    borderRadius: 48,
    borderWidth: 3,
    borderColor: colors.surface,
    overflow: 'hidden',
    backgroundColor: colors.slateSoft,
  },
  shortsAvatarImage: {
    width: '100%',
    height: '100%',
  },
  shortsActionButton: {
    minWidth: 87,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  shortsActionButtonActive: {
    opacity: 1,
  },
  shortsActionText: {
    color: colors.surface,
    fontSize: 17,
    lineHeight: 22,
    fontWeight: '600',
    textAlign: 'center',
  },
  shortsCaption: {
    position: 'absolute',
    left: 25,
    right: 141,
    bottom: 34,
    gap: 11,
    zIndex: 3,
  },
  shortsNameRow: {
    minHeight: 50,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
  },
  shortsVendorName: {
    flexShrink: 1,
    color: colors.surface,
    fontSize: 34,
    lineHeight: 41,
    fontWeight: '700',
  },
  shortsMeta: {
    color: '#D7DEE5',
    fontSize: 20,
    lineHeight: 26,
    fontWeight: '600',
  },
  shortsDescription: {
    color: colors.surface,
    fontSize: 21,
    lineHeight: 29,
    fontWeight: '500',
  },
  shortsButtonRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
    marginTop: 6,
  },
  shortsContactButton: {
    minHeight: 77,
    paddingHorizontal: 24,
    borderRadius: 39,
    backgroundColor: '#27A76F',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 13,
  },
  shortsContactText: {
    color: colors.surface,
    fontSize: 20,
    fontWeight: '600',
  },
  shortsProfileButton: {
    minHeight: 77,
    paddingHorizontal: 24,
    borderRadius: 39,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.34)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 13,
  },
  shortsProfileText: {
    color: colors.surface,
    fontSize: 20,
    fontWeight: '600',
  },
  vendorCard: {
    backgroundColor: colors.surface,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.line,
    overflow: 'hidden',
    shadowColor: colors.ink,
    shadowOpacity: 0.05,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 2,
  },
  vendorCardPressable: {
    padding: 12,
    flexDirection: 'row',
    gap: 12,
  },
  vendorImage: {
    width: 82,
    height: 104,
    borderRadius: 18,
    backgroundColor: colors.tealSoft,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  vendorImagePhoto: {
    width: '100%',
    height: '100%',
  },
  vendorImageText: {
    color: colors.teal,
    fontWeight: '700',
    fontSize: 20,
  },
  vendorInfo: {
    flex: 1,
    gap: 8,
    minWidth: 0,
  },
  vendorCardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 8,
  },
  vendorIdentity: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  vendorNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  availabilityPill: {
    maxWidth: 96,
    paddingVertical: 5,
    paddingHorizontal: 7,
    borderRadius: 7,
    backgroundColor: colors.goldSoft,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 4,
  },
  availabilityText: {
    flexShrink: 1,
    color: colors.gold,
    fontSize: 10,
    lineHeight: 13,
    fontWeight: '600',
  },
  vendorSaveButton: {
    position: 'absolute',
    right: 12,
    bottom: 10,
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  vendorSaveButtonActive: {
    borderColor: colors.coralSoft,
    backgroundColor: colors.coralSoft,
  },
  vendorPriceText: {
    paddingRight: 48,
  },
  vendorMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 12,
  },
  inlineMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  vendorName: {
    color: colors.ink,
    fontWeight: '700',
    fontSize: 17,
    lineHeight: 22,
    flexShrink: 1,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.line,
    gap: 10,
  },
  listCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.line,
    overflow: 'hidden',
  },
  cardTitle: {
    color: colors.ink,
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 21,
  },
  cardText: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 20,
  },
  mutedSmall: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 17,
  },
  errorText: {
    color: colors.coral,
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 18,
  },
  priceText: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: '600',
  },
  statusRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    alignItems: 'center',
  },
  badge: {
    borderRadius: 999,
    paddingVertical: 5,
    paddingHorizontal: 9,
    alignSelf: 'flex-start',
  },
  badgeText: {
    fontSize: 11,
    fontWeight: '600',
  },
  tealBadge: {
    backgroundColor: colors.tealSoft,
  },
  tealBadgeText: {
    color: colors.teal,
  },
  greenBadge: {
    backgroundColor: colors.greenSoft,
  },
  greenBadgeText: {
    color: colors.green,
  },
  goldBadge: {
    backgroundColor: colors.goldSoft,
  },
  goldBadgeText: {
    color: colors.gold,
  },
  coralBadge: {
    backgroundColor: colors.coralSoft,
  },
  coralBadgeText: {
    color: colors.coral,
  },
  mutedBadge: {
    backgroundColor: colors.slateSoft,
  },
  mutedBadgeText: {
    color: colors.muted,
  },
  actionButton: {
    backgroundColor: colors.coral,
    paddingVertical: 13,
    paddingHorizontal: 16,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionButtonText: {
    color: colors.surface,
    fontWeight: '600',
    fontSize: 14,
  },
  buttonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  ghostButton: {
    backgroundColor: colors.surface,
    paddingVertical: 13,
    paddingHorizontal: 16,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: colors.line,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ghostButtonText: {
    color: colors.ink,
    fontWeight: '600',
    fontSize: 14,
  },
  dangerButton: {
    backgroundColor: colors.coralSoft,
    paddingVertical: 13,
    paddingHorizontal: 16,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: colors.coral,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dangerButtonText: {
    color: colors.coral,
    fontWeight: '600',
    fontSize: 14,
  },
  moderationNote: {
    backgroundColor: colors.coralSoft,
    borderLeftWidth: 3,
    borderLeftColor: colors.coral,
    borderRadius: 6,
    padding: 12,
    gap: 4,
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  buttonRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  leadCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.line,
    gap: 8,
  },
  leadCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  leadFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  linkText: {
    color: colors.teal,
    fontSize: 13,
    fontWeight: '600',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  calendarDay: {
    width: '30.5%',
    minHeight: 118,
    backgroundColor: colors.surface,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 12,
    gap: 6,
  },
  calendarDate: {
    color: colors.ink,
    fontSize: 25,
    fontWeight: '700',
  },
  calendarLabel: {
    color: colors.muted,
    fontWeight: '600',
  },
  messageCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.line,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.coralSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    color: colors.coral,
    fontWeight: '700',
    fontSize: 18,
  },
  messageBody: {
    flex: 1,
    gap: 4,
  },
  chatSummaryCard: {
    backgroundColor: colors.surface,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 14,
    gap: 5,
  },
  chatPreview: {
    gap: 8,
  },
  chatBubbleInboundWrap: {
    maxWidth: '86%',
    gap: 4,
  },
  chatBubbleOutboundWrap: {
    maxWidth: '86%',
    alignSelf: 'flex-end',
    gap: 4,
  },
  chatBubbleInbound: {
    maxWidth: '82%',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 18,
    padding: 12,
    color: colors.ink,
    lineHeight: 20,
  },
  chatBubbleOutbound: {
    maxWidth: '82%',
    alignSelf: 'flex-end',
    backgroundColor: colors.teal,
    borderRadius: 18,
    padding: 12,
    color: colors.surface,
    lineHeight: 20,
  },
  chatComposer: {
    minHeight: 58,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
    padding: 8,
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 8,
  },
  chatInput: {
    flex: 1,
    minHeight: 42,
    maxHeight: 120,
    color: colors.ink,
    fontSize: 15,
    lineHeight: 20,
    paddingHorizontal: 10,
    paddingVertical: 10,
    textAlignVertical: 'top',
  },
  chatSendButton: {
    width: 42,
    height: 42,
    borderRadius: 8,
    backgroundColor: colors.coral,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  profileAvatar: {
    width: 62,
    height: 62,
    borderRadius: 31,
    backgroundColor: colors.teal,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileAvatarText: {
    color: colors.surface,
    fontSize: 24,
    fontWeight: '700',
  },
  profileCopy: {
    flex: 1,
  },
  listRow: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  listLabel: {
    color: colors.ink,
    fontWeight: '600',
  },
  listValue: {
    color: colors.muted,
    fontWeight: '600',
  },
  progressBar: {
    height: 10,
    borderRadius: 999,
    backgroundColor: colors.slateSoft,
    overflow: 'hidden',
  },
  progressFill: {
    width: '42%',
    height: '100%',
    backgroundColor: colors.coral,
  },
  detailHeader: {
    backgroundColor: colors.darkBackground,
    borderRadius: 0,
    borderWidth: 0,
    borderColor: 'transparent',
    overflow: 'hidden',
    position: 'relative',
    paddingTop: 34,
    paddingHorizontal: 22,
    paddingBottom: 24,
    gap: 18,
  },
  detailHeaderBackButton: {
    position: 'absolute',
    top: 16,
    left: 16,
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(23, 32, 38, 0.64)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  detailProfileTop: {
    minHeight: 162,
    paddingTop: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 30,
  },
  detailAvatarRing: {
    width: 154,
    height: 154,
    borderRadius: 77,
    borderWidth: 5,
    borderColor: '#F25370',
    padding: 5,
    backgroundColor: '#F5B22C',
    overflow: 'hidden',
  },
  detailAvatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 72,
  },
  detailProfileMain: {
    flex: 1,
    minWidth: 0,
    gap: 22,
  },
  detailNameLine: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  detailProfileStats: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 14,
  },
  detailProfileStat: {
    minWidth: 86,
    gap: 4,
  },
  detailProfileStatValue: {
    color: colors.surface,
    fontSize: 31,
    lineHeight: 37,
    fontWeight: '700',
  },
  detailProfileStatLabel: {
    color: colors.surface,
    fontSize: 20,
    lineHeight: 25,
    fontWeight: '600',
  },
  detailBioBlock: {
    gap: 7,
  },
  detailAvailabilityPill: {
    alignSelf: 'flex-start',
    maxWidth: '100%',
    paddingVertical: 11,
    paddingHorizontal: 14,
    borderRadius: 28,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.16)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 11,
  },
  detailAvailabilityText: {
    flexShrink: 1,
    color: colors.surface,
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 21,
  },
  detailInfo: {
    padding: 22,
    gap: 11,
  },
  detailTitleActionRow: {
    minHeight: 66,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 14,
  },
  detailNameBlock: {
    flex: 1,
    minWidth: 0,
    paddingTop: 1,
  },
  detailTitleActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
  },
  profileIconAction: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.line,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileIconActionActive: {
    backgroundColor: colors.slateSoft,
    borderColor: colors.slateSoft,
  },
  profileContactAction: {
    backgroundColor: colors.coral,
    borderColor: colors.coral,
  },
  detailTitle: {
    color: colors.surface,
    fontSize: 33,
    fontWeight: '700',
    lineHeight: 40,
    flexShrink: 1,
  },
  detailCategoryText: {
    color: '#9CA4AE',
    fontSize: 25,
    lineHeight: 32,
    fontWeight: '500',
  },
  detailPriceLine: {
    color: colors.surface,
    fontSize: 23,
    lineHeight: 30,
    fontWeight: '600',
  },
  detailDescriptionText: {
    color: colors.surface,
    fontSize: 23,
    lineHeight: 31,
    fontWeight: '500',
  },
  detailProfileActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 2,
  },
  detailPrimaryAction: {
    flex: 1,
    minHeight: 66,
    borderRadius: 12,
    backgroundColor: '#4F5DFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
    paddingHorizontal: 16,
  },
  detailPrimaryActionText: {
    color: colors.surface,
    fontSize: 24,
    fontWeight: '600',
  },
  detailSecondaryAction: {
    flex: 1,
    minHeight: 66,
    borderRadius: 12,
    backgroundColor: '#2A2F38',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  detailSecondaryActionText: {
    color: colors.surface,
    fontSize: 24,
    fontWeight: '600',
  },
  detailSmallAction: {
    width: 66,
    height: 66,
    borderRadius: 12,
    backgroundColor: '#2A2F38',
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailStatGrid: {
    flexDirection: 'row',
    gap: 11,
    marginTop: 6,
  },
  detailStat: {
    flex: 1,
    minWidth: 0,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.background,
    padding: 14,
    gap: 6,
  },
  detailStatIcon: {
    width: 38,
    height: 38,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailStatIconTeal: {
    backgroundColor: colors.tealSoft,
  },
  detailStatIconCoral: {
    backgroundColor: colors.coralSoft,
  },
  detailStatIconGold: {
    backgroundColor: colors.goldSoft,
  },
  detailStatValue: {
    color: colors.ink,
    fontSize: 18,
    lineHeight: 23,
    fontWeight: '700',
  },
  detailStatLabel: {
    color: colors.muted,
    fontSize: 15,
    lineHeight: 19,
    fontWeight: '600',
  },
  backButton: {
    alignSelf: 'flex-start',
    paddingVertical: 8,
    paddingHorizontal: 2,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  backButtonText: {
    color: colors.teal,
    fontWeight: '600',
  },
  packageCard: {
    backgroundColor: colors.surface,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 16,
    gap: 12,
  },
  successCard: {
    backgroundColor: colors.greenSoft,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#BFE5D1',
    padding: 16,
    gap: 12,
  },
  portfolioGrid: {
    flexDirection: 'row',
    gap: 8,
  },
  portfolioTile: {
    flex: 1,
    height: 82,
    borderRadius: 8,
    backgroundColor: colors.slateSoft,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  portfolioTileImage: {
    width: '100%',
    height: '100%',
  },
  portfolioTileText: {
    color: colors.teal,
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '600',
    textAlign: 'center',
  },
  profileTabs: {
    minHeight: 68,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    flexDirection: 'row',
    backgroundColor: colors.darkBackground,
  },
  profileTabButton: {
    flex: 1,
    minHeight: 68,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    borderBottomWidth: 3,
    borderBottomColor: 'transparent',
  },
  profileTabButtonActive: {
    borderBottomColor: colors.surface,
  },
  profileTabText: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '600',
  },
  profileTabTextActive: {
    color: colors.surface,
  },
  profileMediaGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 0,
    backgroundColor: colors.darkBackground,
  },
  profileMediaTile: {
    width: '33.333333%',
    aspectRatio: 0.72,
    backgroundColor: colors.slateSoft,
    position: 'relative',
    overflow: 'hidden',
  },
  profileMediaImage: {
    width: '100%',
    height: '100%',
  },
  profileMediaPlayBadge: {
    position: 'absolute',
    top: 7,
    right: 7,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(23, 32, 38, 0.62)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reviewList: {
    gap: 0,
    backgroundColor: colors.darkBackground,
  },
  reviewCard: {
    backgroundColor: colors.surface,
    borderRadius: 0,
    borderWidth: 0,
    borderBottomWidth: 1,
    borderColor: colors.line,
    padding: 20,
    gap: 13,
  },
  reviewAuthorBlock: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  reviewRating: {
    minHeight: 30,
    paddingHorizontal: 9,
    borderRadius: 15,
    backgroundColor: colors.goldSoft,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  reviewRatingText: {
    color: colors.gold,
    fontSize: 12,
    fontWeight: '600',
  },
  portfolioCover: {
    minHeight: 132,
    borderRadius: 18,
    backgroundColor: colors.tealSoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  portfolioCoverImage: {
    width: '100%',
    height: 168,
    borderRadius: 8,
    backgroundColor: colors.slateSoft,
    marginBottom: 4,
  },
  portfolioVideoCover: {
    width: '100%',
    height: 168,
    borderRadius: 8,
    backgroundColor: colors.ink,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  portfolioCoverText: {
    color: colors.teal,
    fontSize: 28,
    fontWeight: '700',
  },
  mediaSelectionRow: {
    gap: 12,
    paddingRight: 16,
  },
  mediaPreviewItem: {
    width: 136,
    gap: 6,
  },
  mediaPreviewImage: {
    width: 136,
    height: 104,
    borderRadius: 8,
    backgroundColor: colors.slateSoft,
  },
  mediaVideoPreview: {
    width: 136,
    height: 104,
    borderRadius: 8,
    backgroundColor: colors.ink,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  mediaVideoTitle: {
    color: colors.surface,
    fontSize: 16,
    fontWeight: '700',
  },
  mediaVideoLabel: {
    position: 'absolute',
    left: 8,
    bottom: 8,
    backgroundColor: colors.ink,
    borderRadius: 6,
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  mediaDurationLabel: {
    position: 'absolute',
    right: 8,
    bottom: 8,
    backgroundColor: colors.ink,
    borderRadius: 6,
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  mediaCoverBadge: {
    position: 'absolute',
    top: 8,
    left: 8,
    backgroundColor: colors.ink,
    borderRadius: 6,
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  mediaCoverBadgeText: {
    color: colors.surface,
    fontSize: 10,
    fontWeight: '600',
  },
  mediaPreviewName: {
    color: colors.ink,
    fontSize: 12,
    fontWeight: '600',
  },
  mediaPreviewActions: {
    minHeight: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  uploadProgressBlock: {
    gap: 8,
  },
  uploadProgressTrack: {
    height: 9,
    borderRadius: 5,
    backgroundColor: colors.slateSoft,
    overflow: 'hidden',
  },
  uploadProgressFill: {
    height: '100%',
    backgroundColor: colors.teal,
  },
  removeText: {
    color: colors.coral,
    fontSize: 12,
    fontWeight: '600',
  },
  mediaCounter: {
    alignSelf: 'flex-start',
    backgroundColor: colors.slateSoft,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  emptyState: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: 22,
    borderWidth: 1,
    borderColor: colors.line,
    alignItems: 'center',
    gap: 8,
  },
  dataState: {
    backgroundColor: colors.surface,
    borderRadius: 8,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.line,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  emptyTitle: {
    color: colors.ink,
    fontSize: 18,
    fontWeight: '700',
  },
  tabBar: {
    position: 'absolute',
    left: 14,
    right: 14,
    bottom: Platform.OS === 'ios' ? 18 : 12,
    backgroundColor: colors.surface,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    shadowColor: colors.ink,
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  tabItem: {
    flex: 1,
    alignItems: 'center',
    gap: 5,
    paddingVertical: 7,
  },
  tabDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: 'transparent',
  },
  tabDotActive: {
    backgroundColor: colors.coral,
  },
  tabText: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: '600',
  },
  tabTextActive: {
    color: colors.ink,
  },
  pressed: {
    opacity: 0.72,
  },
  bootstrapping: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    backgroundColor: colors.background,
  },
  bootLogo: {
    width: 86,
    height: 86,
    borderRadius: 43,
    backgroundColor: colors.slateSoft,
  },
  bootstrappingTitle: {
    color: colors.ink,
    fontSize: 22,
    fontWeight: '700',
  },
  bootstrappingText: {
    color: colors.muted,
    fontSize: 14,
    marginTop: 8,
  },
});
